Sharaya
foliospace/foliospace pull request #4
Opened 2019-05-02 05:51 UTC by bakersha

Hey team,
Please take a look at the server routes that I've sketched out. 
My gitignore doesn't seem to actually be ignoring the node modules, so I apologize for that; not sure how to remedy. The files I'm most concerned about are:
/server
-- index.js
-- /routes
---- general.js
---- account.js
---- admin.js
---- portfolio.js
---- projects.js

Thanks :)

2019-05-02 16:29 UTC, artliou requested changes
Looks great. Could you remove the node_modules folder items from the PR?

I have a .gitignore that includes node_modules.

2019-05-03 03:15 UTC, bakersha commented
Is there a way to do that without starting the PR over again? Can't seem to figure it out.

2019-05-03 16:39 UTC, artliou commented
@bakersha If you go to the "Files Changed" tab, I think you can delete each module/folder independently.

2019-05-04 18:05 UTC, artliou approved these changes

2019-05-04 19:50 UTC, merged